name: Q Code Transformation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  q-code-transformation:
    # Only run if the source branch starts with Q-TRANSFORM-issue-
    if: startsWith(github.head_ref, 'Q-TRANSFORM-issue-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Detect Java version from pom.xml
        id: java-version
        run: |
          JAVA_VER=$(grep -o '<java.version>[^<]*</java.version>' pom.xml | sed 's/<[^>]*>//g' | head -1)
          echo "Detected Java version: $JAVA_VER"
          if [[ "$JAVA_VER" == "17" ]]; then
            echo "version=17" >> $GITHUB_OUTPUT
            echo "maven-version=17" >> $GITHUB_OUTPUT
          else
            echo "version=8" >> $GITHUB_OUTPUT  
            echo "maven-version=1.8" >> $GITHUB_OUTPUT
          fi
          
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.java-version.outputs.version }}
          distribution: 'adopt'

      - name: Build and copy dependencies
        run: |
          mvn -Djava.version=${{ steps.java-version.outputs.maven-version }} -Dmaven.compiler.source=${{ steps.java-version.outputs.maven-version }} -Dmaven.compiler.target=${{ steps.java-version.outputs.maven-version }} verify
          mvn dependency:copy-dependencies -DoutputDirectory=dependencies -Dmdep.useRepositoryLayout=true -Dmdep.copyPom=true -Dmdep.addParentPoms=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: q-code-transformation-dependencies
          path: dependencies
